# fly.toml app configuration file generated for care-chronicle on 2023-09-08T10:51:17-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "care-chronicle"
primary_region = "iad"

[build]

[env]
  PORT = "3000"

[processes]
  app = "node build/src/index.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
